### ISSUE TITLE
Error > Cannot read property 'isValid' of undefined

### ISSUE THREAD

**Issue by thomas3577** [fairmanager/fm-timepicker#5]
Hi,

I always get this error:
TypeError: Cannot read property 'isValid' of undefined

The same error I see on your own demo website:
http://fairmanager.github.io/fm-timepicker/demo.html

**Comment by oliversalzburg** [comment]
Thanks a lot for reporting this! Fixed and published as [3.0.6](https://github.com/fairmanager/fm-timepicker/releases/tag/3.0.6).

**Comment by thomas3577** [comment]
Hi,

 

Wow! Thank you too… for the superfast reaction. :) Can you update the npm-package?

 

https://www.npmjs.com/package/fm-timepicker

 

Best Regards,

Thomas

**Comment by oliversalzburg** [comment]
Whoops. Forgot about that. It's published now :)
