### ISSUE TITLE
Option to allow empty value

### ISSUE THREAD

**Issue by thomas3577** [fairmanager/fm-timepicker#9]
Can you add a option to allow empty value?

**Comment by oliversalzburg** [comment]
Sounds like a great idea. Will be added. But it'll take some time as I have a vacation coming up. PR welcome ;)

**Comment by oliversalzburg** [comment]
@thomas3577 Please have a look at dd8e384f33cdce16e2533b1ecb12b09b10a09635 and let me know if that works for you. http://fairmanager.github.io/fm-timepicker/demo.html is also updated if you want an example.

**Comment by thomas3577** [comment]
Oh wow! Thank you! I think that will work for me.

**Comment by oliversalzburg** [comment]
@thomas3577 Let me know if it works out and I'll wrap up a new release after integrating this into fm-datepicker as well.

**Comment by thomas3577** [comment]
@oliversalzburg Now, I implemented your changes in my project and all works fine. Thank you.

**Comment by oliversalzburg** [comment]
@thomas3577 Awesome :) I'm glad to hear that. Expect a proper release soon. This will probably be a major release though, as it is a breaking change.

**Comment by thomas3577** [comment]
Sorry but I discovered something :-(

I tried to set ng-model = null. This throw an error. And if i set the ng-model = undefined then the timepicker automatically set the current time.
If your timepicker allow empty value, then i think it should be possible to set ng-model = null.

**Comment by oliversalzburg** [comment]
@thomas3577 Please give 6a01311b50c7d6db930f2944fe83cd69a736f547 a try.

**Comment by thomas3577** [comment]
@oliversalzburg Thank you. I implemented this version in my project. This version works find.

**Comment by thomas3577** [comment]
@oliversalzburg Can you make a release of this?

**Comment by oliversalzburg** [comment]
@thomas3577 Released as 6.0.0
